export const HOME = "/";
export const SIGN_UP = "/signup";
export const SIGN_IN = "/signin";
export const FOOTER = "/";
export const SEARCH = "/search";
export const ACCOUNT = "/account";
export const PASSWORD_FORGET = "/settings/pwforget";
export const PASSWORD_CHANGE = "/settings/pwchange";
// export const CREATE_PROJECT = "/createproject";
export const MY_REVIEWS = "/account/reviews";
export const MY_PROJECTS = "/account/projects";
export const SETTINGS = "/settings"
export const MORE_INFO = "/register";
export const STRIPE = "/stripe";
